#!/usr/bin/env bash

# Install HAProxy from the specified repository
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy

# Update HAProxy configuration
cat <<EOF >> /etc/haproxy/haproxy.cfg
frontend http
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    server [STUDENT_ID]-web-01 [STUDENT_ID]-web-01:80 check
    server [STUDENT_ID]-web-02 [STUDENT_ID]-web-02:80 check
EOF

# Restart HAProxy service
service haproxy restart

